#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove surface and features
rm -rf  constant/extendedFeatureEdgeMesh
rm -rf  constant/triSurface

cleanCase
cleanExplicitFeatures

#------------------------------------------------------------------------------
